### ISSUE TITLE
Setting font_color in input_text sets it for the entire menu.

### ISSUE THREAD

**Issue by Horus645** [l4l/yofi#103]
The following configuration: 

```
font_color = 0xf8f8f2ff

[input_text]
font_color = 0x00ff00ff

[list_items]
font_color = 0xf8f8f2ff
```

Results in:
![image](https://user-images.githubusercontent.com/73939669/164569754-f3adcbe6-fdc0-4865-b1d0-b5b954759a76.png)

However, looking at the configuration, I would expect that setting `font_color` to green under `input_text` would only affect the input text, and the listed items would remain white. 

Maybe I am misunderstanding something about the configuration. If that's the case, I apologize.

**Comment by l4l** [comment]
Yeah, that's a bug. Mindless copy-paste at 7646cd05596e911c3ac48fa1fd4cee7dd34c1757
