### ISSUE TITLE
No allocator thread panicked

### ISSUE THREAD

**Issue by cosmoduff** [l4l/yofi#105]
I just built yofi from master as well as the 0.1.5 tag and when executing `yofi apps` I get the following error:

```
❯ yofi apps
thread '<unnamed>' panicked at 'Must provide allocators in no-stdlib code', /home/griff/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.2/src/ffi/alloc_util.rs:185:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Must provide allocators in no-stdlib code', /home/griff/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.2/src/ffi/alloc_util.rs:185:13
thread '<unnamed>' panicked at 'Must provide allocators in no-stdlib code', /home/griff/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.2/src/ffi/alloc_util.rs:185:13
thread '<unnamed>' panicked at 'Must provide allocators in no-stdlib code', /home/griff/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.2/src/ffi/alloc_util.rs:185:13
thread '<unnamed>' panicked at 'Must provide allocators in no-stdlib code', /home/griff/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.2/src/ffi/alloc_util.rs:185:13
[2022-04-27][20:48:47][yofi][ERROR] panic: Must provide allocators in no-stdlib code
```
I tracked down the crate generating the error. It is a dependency of `allsorts_no_std` which is a dependency of `rust-fontconfig`. The `allsorts_no_std` crate has `brotli-decompressor` as a dependency with default features off making it no_std and requiring that an allocator be set. It looks like `allsorts_no_std` may have moved to `allsorts` and likely might just need to be updated.

Let me know if you have any questions, need additional info, or would like me to assist in troubleshooting further.

**Comment by l4l** [comment]
That's crate is kinda pain in the ass, huh. `allsorts_no_std` is a unmaintained [fork](https://github.com/fschutt/allsorts/tree/no_std) of `allsorts` by rust-fontconfig author. So I simply cannot override it without manual patching. As a workaround you may try different backend, fotkit: `cargo b --release --no-default-features --features font-fontkit`.

I wounder though why it fails for your setup. May you provide output of `ldd $(which yofi)` and `strace -e open,openat $(which yofi)`?

**Comment by l4l** [comment]
Hm, I just remembered there's a similar case described at #88. Could you try this patch (i.e just add `allsorts = "0.8.0"` to Cargo.toml)?

**Comment by cosmoduff** [comment]
Adding allsorts as a dependency did fix the issue. As you hinted at in 88 the entire all_srts crate is not necessary. It seems because all_sorts declares brotli-decompressor as a dependency with default feautures it is built with std lib support. I tested just adding `brotli-decompressor = "2.3"` to the dependencies for yofi and that worked as well. I could create a PR for this if you would like me to.

**Comment by l4l** [comment]
Yeah, sure
