### ISSUE TITLE
Suggest adding --prompt (`-p`) to dialog option for setting a menu title

### ISSUE THREAD

**Issue by firecat53** [l4l/yofi#108]
Another small suggestion for the dialog mode to allow setting a title (prompt) for a set of options. This would be the same as the `dmenu -p` or `bemenu --prompt` option.

Thanks!

**Comment by l4l** [comment]
Thanks for the request though you a little bit late. The feature is already supported after #100. It's not released yet though hopefully will do it this/next week.
