### ISSUE TITLE
Crash: failed to initialize fontconfig

### ISSUE THREAD

**Issue by hissssst** [l4l/yofi#137]
```
$ nix shell github:l4l/yofi
$ yofi
[2023-01-30][18:51:43][yofi::input][ERROR] failed to map keyboard on seat seat0: XKBNotFound
thread 'main' panicked at 'failed to initialize fontconfig', src/font/fdue.rs:15:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-01-30][18:51:43][yofi][ERROR] panic: failed to initialize fontconfig
```

**Comment by Aleksanaa** [comment]
> 

Also for me, nixos with hyprland

**Comment by l4l** [comment]
Yeah, nixpkg seems to be broken after #129, the fontconfig dependency need to be specified I guess. Contribution is really welcome here as I don't really use it myself

**Comment by Aleksanaa** [comment]
I've added `--prefix LD_LIBRARY_PATH : ${fontconfig.lib}/lib` to wrapProgram and it is recognized but I get `thread 'main' panicked at 'cannot load default font: The face index is larger than the number of faces in the font.', src/font/fdue.rs:122:14
`

**Comment by figsoda** [comment]
https://github.com/l4l/yofi/pull/138 fixes the issue for me
