### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by jackinloadup** [l4l/yofi#14]
If a `.desktop` file uses an invalid `Exec` yofi fails silently. It panics with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(ENOENT)', src/mode/apps.rs:92:41
```

What I expected was an error letting me know the application failed to launch.

What may be helpful for users debugging issues like this may be to include the .desktop file location in case they have an invalid override in their home folder like myself. Also the Exec that was trying to be run.

**Comment by l4l** [comment]
You may launch yofi with `--verbose` flag and then log file (`/tmp/yofi/log` by default) should contain command to be executed. Afair there's no desktop file logging and that indeed might be useful.

**Comment by l4l** [comment]
182ee57 should do the thing, does it fulfill your needs?

**Comment by jackinloadup** [comment]
Yeah, Looks great! Thanks!

The app is great. I really enjoy how quick the startup is compared to other solutions I've tried when switching from i3 to sway.
