### ISSUE TITLE
Add option to draw border around yofi window

### ISSUE THREAD

**Issue by Aleksanaa** [l4l/yofi#140]
We often make the theme color of launchers the same as apps, and a border (with a different color) makes yofi more noticable. So a border with size and color options would be appreciated.

**Comment by l4l** [comment]
Sounds nice. The implementation is fairly easy:

- pass two config params;
- draw a border [here](https://github.com/l4l/yofi/blob/master/src/draw/background.rs#L29) with `PathBuilder::arc`, maybe with [RoundedRect](https://github.com/l4l/yofi/blob/master/src/draw.rs#L87)

If no one would take the issue I'm likely to implement it this/next weekend

**Comment by Aleksanaa** [comment]
> Sounds nice. The implementation is fairly easy:
> 
>     * pass two config params;
> 
>     * draw a border [here](https://github.com/l4l/yofi/blob/master/src/draw/background.rs#L29) with `PathBuilder::arc`, maybe with [RoundedRect](https://github.com/l4l/yofi/blob/master/src/draw.rs#L87)
> 
> 
> If no one would take the issue I'm likely to implement it this/next weekend

I'd like to implement a lot of things but I don't write rust, so what I can do is simply pointing things out🥲

**Comment by KuabeM** [comment]
I had a quick look and it seems pretty easy. I'd take a shot at this :)
