### ISSUE TITLE
uses outdated rust compiler version

### ISSUE THREAD

**Issue by steven-omaha** [l4l/yofi#145]
https://github.com/l4l/yofi/blob/master/rust-toolchain pins the rustc version to 1.64.0. The project compiles fine under 1.71.0. There seems to be no reason to pin the version.

**Comment by l4l** [comment]
It should work with any version indeed but reproducibility matters. I don't want CI lint job to be broken without explicit compiler update, nor try to remember which compiler version was used for a particular release.

I eventually update the pinned version, but users shouldn't really care about it, that's only for the devs who able modify it anyway. Formally, yofi has no [MSRV](https://rust-lang.github.io/rfcs/2495-min-rust-version.html) but rust-toolchain could be considered as the one, i.e any version equal or greater should work fine (previous versions might also work but not guaranteed).
