### ISSUE TITLE
Configuration: specifiy font size

### ISSUE THREAD

**Issue by KuabeM** [l4l/yofi#15]
First of all, looks quite nice what you got here! I like what I've seen after playing with it a bit

Anyway, I noticed that the font on my setup appears a notch too large and I'd like to use a smaller font size. I haven't seen a hint in the example config, so is this already possible through the config? 

If not and you're interested in getting help, I'd like to give it a shoot and try implementing this feature.

**Comment by l4l** [comment]
Oops, thanks for noticing, forgot to update the readme file. The feature was already implemented in https://github.com/l4l/yofi/commit/1a34eb29b8219f39787f56e6aedf5b7f627ff179 (yet no release for that fix) so all you need is to add `font_size = 14` to config file.

**Comment by l4l** [comment]
Added to sample config at readme: https://github.com/l4l/yofi/commit/1dc20840a2543ece1f93073c1f5ee23060e28aa2

**Comment by KuabeM** [comment]
Nice, thank you!
