### ISSUE TITLE
Panic on launch after Hyprland update

### ISSUE THREAD

**Issue by crispywaffles666** [l4l/yofi#152]
After applying the latest Hyprland update yofi will no longer launch.

I have duplicated this on two different machines and tried running Hyprland with the default config to rule out an issue with my configs.

Attempting to run from a terminal creates the following output:

```plaintext
[2023-12-16][20:41:06][yofi][WARN] cannot read blacklist file "/home/user/.config/yofi/blacklist": No such file or directory (os error 2)
interface 'wl_surface' has no event 2
thread 'main' panicked at 'called Result::unwrap() on an Err value: OtherError(Os { code: 0, kind: Uncategorized, message: "Success" })', src/main.rs:242:44
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
[2023-12-16][20:41:06][yofi][ERROR] panic: called Result::unwrap() on an Err value: OtherError(Os { code: 0, kind: Uncategorized, message: "Success" })
```

I am on Arch Linux and have tried both the `yofi` and `yofi-git` AUR packages. Hyprland is from the Arch repos.

I have confirmed that yofi still works in sway. So perhaps this is related to a newer build of wlroots, or something else specific to Hyprland.

I would be happy to provide further information if needed.

**Comment by filtsin** [comment]
The same thing happened with wezterm and other rust apps using sctk. (wezterm: https://github.com/wez/wezterm/issues/4483)
sctk 0.16.1 fix the problem

**Comment by crispywaffles666** [comment]
> The same thing happened with wezterm and other rust apps using sctk. (wezterm: [wez/wezterm#4483](https://github.com/wez/wezterm/issues/4483)) sctk 0.16.1 fix the problem. I created pull request for this change

I have tried your branch and confirmed this resolves the issue. Thanks.
