### ISSUE TITLE
crash when setting match_color in config file

### ISSUE THREAD

**Issue by sstark** [l4l/yofi#17]
I use the yofi 0.1.3 binaries for ubuntu 20.04 on manjaro linux (but also happens with the self-compiled one). If I use the default settings, all is working as it should. As soon as I configure _match_color_ in `~/.config/yofi/yofi.config`, yofi would suddenly crash in the middle of typing. Here is the result of starting yofi and typing the characters `n` and `e`:

```
env RUST_BACKTRACE=full yofi
thread 'main' panicked at 'assertion failed: r.end <= x.chars().count()', src/draw/list_view.rs:142:17
stack backtrace:
   0:     0x5558a572e69a - <unknown>
   1:     0x5558a56613ac - <unknown>
   2:     0x5558a572de01 - <unknown>
   3:     0x5558a572d70b - <unknown>
   4:     0x5558a582a8d3 - <unknown>
   5:     0x5558a582a8ac - <unknown>
   6:     0x5558a582a88a - <unknown>
   7:     0x5558a585e478 - <unknown>
   8:     0x5558a582d30b - <unknown>
   9:     0x5558a560c678 - <unknown>
  10:     0x5558a582a863 - <unknown>
  11:     0x5558a5613275 - <unknown>
  12:     0x7f3f74060152 - __libc_start_main
  13:     0x5558a55f10be - <unknown>
  14:                0x0 - <unknown>
```

I guess the exact characters depend on which programs are in my list, so I don't really know how I can describe how to reproduce it. For me it is 100% reproducible. Also happens if I just press `p` and for many other key sequences.

I am sorry that above stacktrace does not look very useful, how would I get a better one?

**Comment by l4l** [comment]
For some time of typing random letters I indeed can reproduce the issue, hopefully b99005747308d8f8af0da5c427f414b15d5e919e should be enough for that fix. May you check that it works for you?

**Comment by sstark** [comment]
That fixes it for me! Thanks a lot for the fast patch and a great launcher!
