### ISSUE TITLE
How to use blacklist file on yofi

### ISSUE THREAD

**Issue by Mr-FuzzyPenguin** [l4l/yofi#175]
Edit cause: I realized that it was a different problem unrelated to yofi, related to my system. However, I would like to now know instead, how to use the blacklist feature.

**Comment by Mr-FuzzyPenguin** [comment]
I fixed it, I think it was something wrong with my config. For some reason it cannot search in Adwaita anymore. I do have the Adwaita directory in /usr/share/icons/Adwaita/* but I don't know why if I put Adwaita it breaks.

**Comment by l4l** [comment]
Here's the doc: https://github.com/l4l/yofi/wiki/Configuration#entries-blacklisting
