### ISSUE TITLE
Blacklist not working?

### ISSUE THREAD

**Issue by moberer** [l4l/yofi#178]
Unfortunately I've got some Audio-Plugins installed, which clutter up the search.
Since yofi offers blacklisting unwanted applications, I tried to do that.

Unfortunately, the blacklisted applications still show up, even though I added them to my list.

Location of the offending .desktop files:
```
$ locate .desktop | rg lsp
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x2_mono.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x2_stereo.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x4_mono.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x4_stereo.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x8_mono.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x8_stereo.desktop
...
```

Content of ~/.config/yofi/blacklist:
```
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x2_mono.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x2_stereo.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x4_mono.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x4_stereo.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x8_mono.desktop
/usr/share/applications/in.lsp_plug.lsp_plugins_ab_tester_x8_stereo.desktop
...
```

As far as I understand, this should work, shouldn't it?
Or is there anything else I could try?

Thank you for your otherwise great launcher!

**Comment by l4l** [comment]
Well, that's actually works only with the _filenames_, not _filepaths_, so it should be:

```
in.lsp_plug.lsp_plugins_ab_tester_x2_mono.desktop
in.lsp_plug.lsp_plugins_ab_tester_x2_stereo.desktop
in.lsp_plug.lsp_plugins_ab_tester_x4_mono.desktop
...
```

Perhaps the path shall be also allowed.

**Comment by moberer** [comment]
Thank you for your quick answer, that managed to resolve my issue!

[Also, as a note for anyone having the same problem: The blacklist is only active when calling `yofi` directly and *not* for `yofi apps`, which will still show everything.]

**Comment by moberer** [comment]
I added an example to the wiki to make this clearer for future users;
Hope that's alright for you;
