### ISSUE TITLE
Can't launch gedit as "gedit"

### ISSUE THREAD

**Issue by alanorth** [l4l/yofi#26]
Testing yofi snapshot (377497b134970347ae91a71320cf31d046342d33) from 2020-12-30. I notice that I can't launch gedit by typing "gedit". I have to type something that matches "Text Editor" instead. Is yofi only checking the `Name` entries of desktop files?

I see the `/usr/share/applications/org.gnome.gedit.desktop` file on Arch Linux has the following:

```
Keywords[en_GB]=Text;Editor;Plaintext;Write;gedit;
```

Could it be possible add support for matching these keywords?

**Comment by l4l** [comment]
Sure, that is a reasonable enchantment. Current version only supports searching by "Name" field indeed.

**Comment by alanorth** [comment]
The `origin/keyword-search` branch works great. Thanks!
