### ISSUE TITLE
Yofi isn't finding Flatpak .desktop files

### ISSUE THREAD

**Issue by PopeRigby** [l4l/yofi#31]
`XDG_DATA_DIRS` is set to `/usr/local/share /usr/share $HOME/.local/share/ $HOME//.local/share/flatpak/exports/share`, but Yofi isn't finding their desktop files.

**Comment by l4l** [comment]
`XDG_DATA_DIRS` directories should be separated with a colon (`:`), not a space[¹].

P.S. `$HOME/.local/share/` directory implies from empty `XDG_DATA_HOME`; adding it to `XDG_DATA_DIRS` makes yofi traverse it twice (entries are still de-duplicated, but that's a useless work anyway).

[¹]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#introduction

**Comment by PopeRigby** [comment]
> `XDG_DATA_DIRS` directories should be separated with a colon (`:`), not a space[¹](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#introduction).

Right you are. I'm using fish, so I just assumed it would be handled the same as path. Thanks.
