### ISSUE TITLE
Fix font kerning totally not accounted for.

### ISSUE THREAD

**Issue by nikp123** [l4l/yofi#46]
Hello, I'd like to raise a issue about how this program does font rendering, as it seems that this program does no kerning (at least properly) at all. Font kerning, which you can read about [here](https://en.wikipedia.org/wiki/Kerning) is the spacing between each letters specified by the font file. This must be obeyed if the text is desired to look properly.

For now, it seems that even the default font suffers from characters overwriting and overlapping each other producing less desirable menu to look at.

Example A:
![image](https://user-images.githubusercontent.com/4696350/118373012-bc21bb00-b5b4-11eb-9d2b-432b58b2503a.png)

You can see that the top of the letter "V" is cut off due to improper kerning and lack of character bitmap blending.

Example B (using the "Terminus TTF" font):
![image](https://user-images.githubusercontent.com/4696350/118373058-f2f7d100-b5b4-11eb-8c14-80422d89c981.png)

The text is not even legible with this font as the kerning is not obeyed at all. I chose this font as it can avoid text blending issues in the 1st example, where each character overrides one another as each character should (in theory) take it's own space and not share "the same pixel space".

I'd purpose that since the code already calculates character pixel offsets, that you also consider per font/character kerning so that the produced render doesn't look so garbled. I, unfortunately, can't help much because of my lack of experience in rust. Wish you the best in remedying this problem :)

**Comment by l4l** [comment]
For now the font rendering behaves really bad indeed, and I guess kerning is not the only problem. You can find related discussion at #39. Possibly #44 may resolve that issue, but it's fairly hard and time-consuming thus perhaps won't be resolved soon.

**Comment by l4l** [comment]
Current version should "just work"

For terminus there's quite weird issue: https://github.com/mooman219/fontdue/issues/91
