### ISSUE TITLE
Support multiple Desktop Actions

### ISSUE THREAD

**Issue by valkum** [l4l/yofi#65]
A single Desktop Entry can have multiple Desktop Actions (see e.g. https://github.com/swaywm/sway/wiki/Tricks#take-screenshots-and-open-them-in-annotation-tool)

It would be nice if this was somehow supported by yofi itself. How much effort would that be?

**Comment by l4l** [comment]
Yeah, quite an expected issue. That's probably would not be hard to implement from tech perspective but it's hard to provide a nice UI, I don't really want to complicate it and support some kind of nested entries list. Perhaps it can be done simply by adding a new hotkey (e.g. right arrow) for switching to the list of actions for selected desktop entry, but I'm not sure whether it's an intuitive or not. Do you have an idea how it should look like?

**Comment by valkum** [comment]
I guess if the entry has at least one action, show a second row for an entry and with a distinct different color/font-size show the actions there. Making that selectable by left and right (with some indicators ->/<-) could look alright.

**Comment by l4l** [comment]
![Screenshot_2021 11 10_15:20:50](https://user-images.githubusercontent.com/5658339/141112121-b6e8c84e-e2ed-4031-9449-775f05e32de7.png)


Something like that layout you mean?

**Comment by l4l** [comment]
#78 adds the feature, though it renders badly (inline). Idk whether I want to change layout at this patch, but the proposed one looks better so I don't want to close that issue yet.
