### ISSUE TITLE
blacklist

### ISSUE THREAD

**Issue by ruizlenato** [l4l/yofi#77]
I saw that yofi has a blacklist, but how does it work, how do I add applications/.desktop to it?

**Comment by l4l** [comment]
Added a wiki page for that: https://github.com/l4l/yofi/wiki/Configuration#entries-blacklisting

TLDR:

1. Find the desktop filename for an unwanted app. E.g.: `grep 'Name=<name-of-the-app>' /usr/share/applications/**/**`.
2. Put this filename to the _$HOME/.config/yofi/blacklist_ (1 line - 1 blacklisted entry).

Hope that helps

**Comment by l4l** [comment]
For [your file](https://github.com/ruizlenato/dotfiles/blob/main/.config/yofi/blacklist) you missed `.desktop` suffix.
