### ISSUE TITLE
Letter distance flawed

### ISSUE THREAD

**Issue by glanch** [l4l/yofi#82]
Using the default config and `yofi 0.1.3` the letter distance when opening yofi is flawed:
![image](https://user-images.githubusercontent.com/49610590/152999387-ec67d278-01c7-437e-ab87-ecb29efb52a3.png)

**Comment by l4l** [comment]
Yep, that happens with the fontkit backend and certain fonts. Starting with the `0.1.5` release the default one is fontdue (#63) which should handle font stuff better so you simply need to update yofi.
