### ISSUE TITLE
Some desktop files makes yofi crash

### ISSUE THREAD

**Issue by Nooguat** [l4l/yofi#84]
Hi,
I tried to use the default config file given in the wiki and I got this error  : `thread 'main' panicked at 'range start index 51 out of range for slice of length 39', src/icon.rs:86:34`
After some investigations I found this file
```
[Desktop Entry]
Name=Code - OSS
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/bin/code-oss --unity-launch %F
Icon=com.visualstudio.code.oss.png
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=TextEditor;Development;IDE;
MimeType=text/plain;application/x-code-oss-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/bin/code-oss --new-window %F
Icon=com.visualstudio.code.oss.png

```
makes yofi crash.

**Comment by l4l** [comment]
That looks like a corrupted image file, may you share it (probably `/usr/share/pixmaps/com.visualstudio.code.oss.png`)? If so reinstalling the package should help.

Anyway, that shouldn't be a panic so thanks for the report.

**Comment by l4l** [comment]
Thanks for the report. That one is fixed in the linked PR and haven't been released yet
