### ISSUE TITLE
libsystemd error: No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by whoizit** [l4l/yofi#89]
Artix Linux s6 init
aur/yofi-git
```
❯ yofi
[2022-03-05][13:50:29][yofi::desktop][WARN] cannot parse DirEntry("/home/user/.local/share/flatpak/exports/share/applications/mimeinfo.cache"): Error parings input: Tag at ``, skipping
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SdError { kind: Generic, msg: "failed to print to journal at '/run/systemd/journal/socket': libsystemd error: No such file or directory (os error 2)" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/systemd-journal-logger-0.5.0/src/lib.rs:308:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by l4l** [comment]
Current build requires systemd installation for logging. I guess you may workaround it by forwarding journald socket to /dev/null or file, e.g `mkdir -p /run/systemd/journal && socat unix-listen:/run/systemd/journal/socket,fork exec:<your_script_here>`.

Do you have some other logging facility one may use instead of journald?

**Comment by whoizit** [comment]
why not use stdout messages by default?

https://skarnet.org/software/s6/s6-log.html

**Comment by l4l** [comment]
Ehm, I use env where stdout isn't really available. But yeah, stdout+
 perhaps a better

**Comment by WojAbuk** [comment]
In my opinion, rsyslog would be better than journald.  In my opinion, it should be possible to disable the dependency on systemd (preferably during compilation).  I hope you understand my English.  https://docs.rs/syslog/latest/syslog/
